### ISSUE TITLE
Slight delay between two replacements

### ISSUE THREAD

**Issue by TobiasBg** [pviswanathan/ChromeAutoTextExpander#6]
When I type two keywords (which are replaced) where quickly, without much of a delay between them, the second one is sometimes not recognized.
My assumption is that that's happening because of the JS string comparisions that the Extension is doing.
Maybe the approach of the Popchrom Extension (see the code at https://code.google.com/p/trnsfrmr/ might be worth a shot)?

**Comment by carlinyuen** [comment]
Hey @TobiasBg do you still see this? I tried to do some minor optimizations on the code, but it is kinda capped by the speed of the chrome.storage.sync.get() calls. :o\ Let me know!

**Comment by TobiasBg** [comment]
Yes, it's still happening. It's not that much of an issue for me anymore, though. By now, my fingers "know" to add a small delay when typing frequently used keywords :-)

**Comment by carlinyuen** [comment]
Ah bummer. :o( Sorry friend, seems like I haven't been able to optimize this enough. Perhaps if I can move off the chrome apis and store a local cached copy of the shortcuts... I'll keep this in mind. Thanks for reporting this and helping with the advice.
