### ISSUE TITLE
Marked as Malware again

### ISSUE THREAD

**Issue by SuperStark** [pviswanathan/ChromeAutoTextExpander#75]
Looks like Google have waved their malware hammer as the plugin is again offline.

**Comment by agacinco** [comment]
is there any way to get the templates back? I forgot to save mine

**Comment by pviswanathan** [comment]
I’m terribly sorry that you are seeing this message. We are in the process of resolving this with Google. We should be back in the store, I request you to not delete the app in the meantime as your data will unfortunately be lost if you do so.

**Comment by pviswanathan** [comment]
I have confirmation from several users that the app has been re-enabled. Sorry again for the inconvenience, I hope you are back up an running like normal.

**Comment by pviswanathan** [comment]
For transparency, more about this, including Google's official response, can be found here: https://getmagical.notion.site/Auto-Text-Expander-Outage-23bff9d3613342d79acef98d6c7c37be

Summary: Google accidentally marked us as malware, recognized their error and apologized for the inconvenience.
