### ISSUE TITLE
Hi @pviswanathan  The extension (Auto Text Expander for Google Chrome Official

### ISSUE THREAD

**Issue by Anumyakala** [pviswanathan/ChromeAutoTextExpander#76]
Hi @pviswanathan  The extension (Auto Text Expander for Google Chrome Official
1.10.4) was just marked with malware again, and it's not reverting back. I am in mid of my work and have lost all the data. Please help.

**Comment by Anumyakala** [comment]
![image](https://user-images.githubusercontent.com/82147918/114005748-79661800-987d-11eb-959a-74d9b57bbb7e.png)

**Comment by pviswanathan** [comment]
I’m terribly sorry that you are seeing this message. We are in the process of resolving this with Google. We should be back in the store, I request you to not delete the app in the meantime as your data will unfortunately be lost if you do so.

**Comment by Anumyakala** [comment]
Hi @pviswanathan It seems to be back up and working now. Thank you for your help :-)
