### ISSUE TITLE
Magical is blocked by admin -- how to install Auto Text Expander v2.0.0?

### ISSUE THREAD

**Issue by alon-to** [pviswanathan/ChromeAutoTextExpander#79]
Background:

- I've been using Auto Text Expander for many years on my work computer
- My work admin has blocked the Magical extensions (see screenshot). This is because corporate policy is to automatically block extensions that are flagged as potentially malicious or requiring high-risk permissions.
- I still have Auto Text Exapnder v1.9.5 on my work computer

Question:
- Are there steps I can follow to install v2.0.0 of Auto Text Expander? The extension page says this version supports Hangouts and Facebook Messenger and I'd like to experiment with it.

**Comment by pviswanathan** [comment]
Sorry for the inconvenience. 

You can access our latest release here: https://chrome.google.com/webstore/detail/magical-%E2%80%93-text-expansion/iibninhmiggehlcdolcilmhacighjamp.

This is the only extension that we maintain, we are not affiliated to any other extensions.
